# application.properties는 주석처리되었습니다. application.yml을 사용합니다.
# server.port=8080
# 
# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USER}
# spring.datasource.password=${DB_PASSWORD}
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# 
# spring.jpa.hibernate.ddl-auto=update
# 
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# spring.sql.init.mode=never
# 
# spring.mvc.pathmatch.matching-strategy=ant_path_matcher
# 
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.com.zaxxer.hikari=DEBUG
